defaults:
  - network: ff_nps
  - _self_

ENV_NAME: scratchitch

ENV_KWARGS:
  ctrl_cost_weight: 0
  homogenisation_method: max
  backend: mjx
  het_reward: False
  disability:
    joint_idx: 13
    joint_restriction_factor: 1.0
    joint_strength: 1.0
    tremor_magnitude: 0.0

TOTAL_TIMESTEPS: 4e7 
NUM_STEPS: 256
NUM_ENVS: 1024 
NUM_SEEDS: 10 
SEED: 0
NUM_EVAL_EPISODES: 32 

PARALLEL_BATCH_SIZE: 1 
MAX_CROSSPLAY_PAIRS: 3  # null = all teams; set to int (e.g. 32) to subsample

crossplay:
  robot_algos: ["IPPO", "MAPPO", "MASAC"]  # which algos to include as partners in crossplay evaluation
  algo_configs:
    IPPO: 
      main: "assistax/baselines/ZSC/config/ppo_aht.yaml"
      network: "assistax/baselines/ZSC/config/network/ff_nps.yaml"
    #MAPPO: 
    #  main: "assistax/baselines/ZSC/config/_aht.yaml"
    #  network: "MAPPO/config/network/ff_nps.yaml"
    #MASAC: 
    #  main: "MASAC/config/masac_aht.yaml"
    #  network: "MASAC/config/network/ff_nps.yaml"


PARTNER_ALGORITHMS: ["IPPO"]

ZOO_PATH: /home/leo/assistive-autonomy-github/assistax/zoo 
GPU_ENV_CAPACITY: 8192
ADVANTAGE_UNROLL_DEPTH: 8
DISABLE_JIT: False
DEVICE: 0

hydra:
  job:
    chdir: true
  run:
    dir: outputs/crossplay/${ENV_NAME}/${now:%Y-%m-%d}/${now:%H-%M-%S}

