"""
IPPO Ad Hoc Teamwork (AHT) Training for Zero-Shot Generalization

This module implements Ad Hoc Teamwork training using IPPO, where agents learn to collaborate
effectively with diverse, pre-trained teammates from a zoo. The goal is to train agents that
can generalize to work with previously unseen partners in zero-shot scenarios.
Usage:
    python ippo_aht.py [hydra options]
    
The script requires a pre-populated zoo (generated by ippo_zoo_gen.py) containing
diverse agents from multiple algorithms.
"""

import os
os.environ.setdefault('MUJOCO_GL', 'egl')
import sys
import time
from tqdm import tqdm
import jax
import jax.numpy as jnp
import flax.linen as nn
from flax.linen.initializers import constant, orthogonal
from flax.training.train_state import TrainState
from flax.traverse_util import flatten_dict
import safetensors.flax
import optax
import distrax
import assistax
from assistax.wrappers.baselines import  get_space_dim, LogEnvState, LogWrapper
from assistax.wrappers.aht import ZooManager, LoadAgentWrapper
import hydra
from omegaconf import OmegaConf
import pandas as pd
from typing import Sequence, NamedTuple, Any, Dict
import wandb
from datetime import datetime
from assistax.baselines.utils import (
    _tree_take, _unstack_tree, _take_episode,
    _tree_shape, _stack_tree, _concat_tree, _tree_split,
    log_all_metrics_zsc, upload_eval_data_to_wandb,
    upload_model_parameters_to_wandb, upload_html_visualizations_to_wandb,
    upload_mujoco_trajectories_to_wandb, upload_mujoco_videos_to_wandb, print_memory_stats
    )
from assistax.baselines.utils import _compute_episode_returns_sweep as _compute_episode_returns
os.environ['XLA_FLAGS'] = (
    '--xla_gpu_triton_gemm_any=True ' # As recommended by MJX for better performance on NVIDIA GPUs
)
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))




# ========================= PARTNER DATA COLLECTION ===========================

def make_collect_partner_data(config, load_zoo_dict, batchify, unbatchify, RunnerState):
    """Create a JIT-able function that collects all partner actions and observations.

    Runs evaluation episodes with the trained robot policy and captures the full
    ``(total_pop_size, action_dim)`` partner action tensor at every step.

    Args:
        config: Hydra config dict.
        load_zoo_dict: Zoo loading dict for partner selection.
        batchify: Agent-dict → stacked-array helper from the IPPO variant.
        unbatchify: Stacked-array → agent-dict helper from the IPPO variant.
        RunnerState: NamedTuple class from the IPPO variant.

    Returns:
        A function ``collect(rng, train_state) -> (all_actions, all_obs)``
        where ``all_actions`` has shape ``(max_steps, num_eps, pop_size, true_act_dim)``
        and ``all_obs`` has shape ``(max_steps, num_eps, obs_dim)``.
    """
    zoo = ZooManager(config["ZOO_PATH"])
    env = assistax.make(config["ENV_NAME"], **config["ENV_KWARGS"])
    env = LoadAgentWrapper.load_from_zoo(env, zoo, load_zoo_dict)
    env = LogWrapper(env, replace_info=True)

    num_eps = config["NUM_EVAL_EPISODES"]
    max_steps = env.episode_length
    loaded_agent = env._env.loaded_agents[0]  # e.g. "human"
    true_act_dim = env._env._env.agent_action_mapping[loaded_agent].size

    def collect(rng, train_state):
        rng_reset, rng_run = jax.random.split(rng)
        rngs_reset = jax.random.split(rng_reset, num_eps)
        init_dones = jnp.zeros((env.num_agents, num_eps), dtype=bool)

        obsv, env_state = jax.vmap(env.reset)(rngs_reset)
        runner_state = RunnerState(
            train_state=train_state,
            env_state=env_state,
            last_obs=obsv,
            last_done=init_dones,
            update_step=0,
            rng=rng_run,
        )

        def _collect_step(runner_state, unused):
            rng = runner_state.rng

            # Robot policy forward pass
            obs_batch = batchify(runner_state.last_obs, env.agents)
            avail_actions = jax.vmap(env.get_avail_actions)(
                runner_state.env_state.env_state
            )
            avail_actions = jax.lax.stop_gradient(
                batchify(avail_actions, env.agents)
            )
            ac_in = (obs_batch, runner_state.last_done, avail_actions)

            (actor_mean, actor_std), _ = runner_state.train_state.apply_fn(
                runner_state.train_state.params, ac_in,
            )
            actor_std = jnp.expand_dims(actor_std, axis=1)
            pi = distrax.MultivariateNormalDiag(actor_mean, actor_std)
            rng, act_rng = jax.random.split(rng)
            action, _ = pi.sample_and_log_prob(seed=act_rng)
            env_act = unbatchify(action, env.agents)

            # Capture partner obs *before* step (matches the obs partners acted on)
            partner_obs = runner_state.last_obs[loaded_agent]  # (num_eps, obs_dim)

            # Step the environment
            rng, step_rng = jax.random.split(rng)
            rng_step = jax.random.split(step_rng, num_eps)
            obsv, env_state, reward, done, info = jax.vmap(env.step)(
                rng_step, runner_state.env_state, env_act,
            )
            done_batch = batchify(done, env.agents)

            # Extract all partner actions stored by LoadAgentWrapper.step()
            all_partner_acts = env_state.env_state.all_partner_actions[loaded_agent][..., :true_act_dim]

            runner_state = RunnerState(
                train_state=runner_state.train_state,
                env_state=env_state,
                last_obs=obsv,
                last_done=done_batch,
                update_step=runner_state.update_step,
                rng=rng,
            )
            return runner_state, (all_partner_acts, partner_obs)

        _, (all_actions, all_obs) = jax.lax.scan(
            _collect_step, runner_state, None, max_steps
        )
        # all_actions: (max_steps, num_eps, pop_size, act_dim)
        # all_obs:     (max_steps, num_eps, obs_dim)
        return all_actions, all_obs

    return collect


# ================================ MAIN AHT TRAINING FUNCTION ================================

@hydra.main(version_base=None, config_path="config", config_name="ppo_aht")
def main(config):
    """
    Main function for Ad Hoc Teamwork training using IPPO with zoo-based partners.
    
    This function implements a sophisticated training pipeline for zero-shot generalization:
    1. Loads diverse pre-trained partners from zoo across multiple algorithms
    2. Creates train/test splits for proper generalization evaluation
    3. Trains new agents against the training set of diverse partners
    4. Evaluates on both train and test sets to measure generalization capability
    5. Saves comprehensive results for analysis of AHT performance
    
    The resulting agents should be able to collaborate effectively with previously
    unseen teammates, demonstrating robust teamwork and adaptability.
    
    Args:
        config: Hydra configuration object containing AHT training parameters,
               partner algorithms, and zoo specifications
    """
    config = OmegaConf.to_container(config, resolve=True)

    # ===== DYNAMIC ALGORITHM SELECTION =====
    # Import the appropriate IPPO variant based on network architecture configuration
    match (config["network"]["recurrent"], config["network"]["agent_param_sharing"]):
        case (False, False):
            from IPPO.ippo_ff_nps import make_train, make_evaluation, EvalInfoLogConfig, batchify, unbatchify, RunnerState
            print("Using: Feedforward Networks with No Parameter Sharing")
        case (False, True):
            from IPPO.ippo_ff_ps import make_train, make_evaluation, EvalInfoLogConfig, batchify, unbatchify, RunnerState
            print("Using: Feedforward Networks with Parameter Sharing")
        case (True, False):
            from IPPO.ippo_rnn_nps import make_train, make_evaluation, EvalInfoLogConfig, batchify, unbatchify, RunnerState
            print("Using: Recurrent Networks with No Parameter Sharing")
        case (True, True):
            from IPPO.ippo_rnn_ps import make_train, make_evaluation, EvalInfoLogConfig, batchify, unbatchify, RunnerState
            print("Using: Recurrent Networks with Parameter Sharing")

    # ===== WANDB INIT =====
    now = datetime.now()
    ps_tag = "ps" if config["network"]["agent_param_sharing"] else "nps"
    rec_tag = "rnn" if config["network"]["recurrent"] else "ff"
    env_name = config.get("ENV_NAME", "").lower()
    alg_name = config.get("ALG", "PPO_AHT").lower()
    name = f"{alg_name}_{ps_tag}_{rec_tag}_{env_name}_{config['EXP_ID']}_seed{config['SEED']}"
    tags = [config["EXP_ID"]] + config.get("EXP_TAGS", []) + [env_name] + [alg_name]
    config["EXP_TAGS"] = tags
    run = wandb.init(
        entity=config["ENTITY"],
        project=config["PROJECT"],
        tags=tags,
        config=config,
        mode=config["WANDB_MODE"],
        reinit=True,
        name=name,
        save_code=True,
    )

    # ===== TRAINING SETUP =====
    rng = jax.random.key(config["SEED"])
    train_rng, eval_rng = jax.random.split(rng)
    train_rngs = jax.random.split(train_rng, config["NUM_SEEDS"])
    
    print(f"Starting Ad Hoc Teamwork training with {config['TOTAL_TIMESTEPS']} timesteps")
    print(f"Num environments: {config['NUM_ENVS']}")
    print(f"Num seeds: {config['NUM_SEEDS']}")
    print(f"Environment: {config['ENV_NAME']}")
    print(f"Zoo path: {config['ZOO_PATH']}")
    print(f"Training algorithm: {config['ALGORITHM']}")
    print(f"Partner algorithms: {config['PARTNER_ALGORITHMS']}")
    
    # ===== ZOO MANAGEMENT AND PARTNER SELECTION =====
    print("Loading zoo and selecting diverse partners...")
    with jax.disable_jit(config["DISABLE_JIT"]):
        zoo = ZooManager(config["ZOO_PATH"])
        alg = config["ALGORITHM"]
        scenario = config["ENV_NAME"]
        
        # Load partners from multiple algorithms for diversity
        partner_dict = {}
        for partner_algo in config["PARTNER_ALGORITHMS"]:
            partner_dict[partner_algo] = zoo.index.query(f'algorithm == "{partner_algo}"'
                                                         ).query(f'scenario == "{scenario}"'
                                                            ).query('scenario_agent_id == "human"')
            print(f"Found {len(partner_dict[partner_algo])} {partner_algo} partners")
        
        # ===== TRAIN/TEST SPLIT FOR GENERALIZATION EVALUATION =====
        # Critical for measuring zero-shot generalization capability
        print("Creating train/test splits for generalization evaluation...")
        all_partners = pd.concat(partner_dict.values(), ignore_index=True)
        print(f"Total partners across all algorithms: {len(all_partners)}")

        if "EXTREME_SPLIT" in config and config["EXTREME_SPLIT"] is not None:
            # Extreme-based split
            from assistax.baselines.ZSC.aht_utils import split_partners_extreme
            extreme_cfg = config["EXTREME_SPLIT"]
            extreme_set, remainder_set = split_partners_extreme(all_partners, extreme_cfg)

            role = extreme_cfg.get("role", "test")
            if role == "test":
                test_partners, train_partners = extreme_set, remainder_set
            else:
                train_partners, test_partners = extreme_set, remainder_set

            print(f"Extreme split: {len(extreme_set)} extreme agents -> {role} set")
        else:
            # Original random split
            train_partners = all_partners.sample(frac=config["SPLIT_RATIO"], random_state=42)
            test_partners = all_partners.drop(train_partners.index)

        # Split back into algorithm-specific dictionaries
        train_set = {}
        test_set = {}

        for algo in partner_dict.keys():
            train_set[algo] = train_partners[train_partners['algorithm'] == algo].reset_index(drop=True)
            test_set[algo] = test_partners[test_partners['algorithm'] == algo].reset_index(drop=True)
            print(f" {algo}: {len(train_set[algo])} train, {len(test_set[algo])} test partners")

        # Create zoo loading dictionaries for training and testing
        load_zoo_dict_train = {algo: {"human": list(train_set[algo].agent_uuid)} for algo in partner_dict.keys()}
        load_zoo_dict_test = {algo: {"human": list(test_set[algo].agent_uuid)} for algo in partner_dict.keys()}

        print(f"Training against {sum(len(train_set[algo]) for algo in train_set)} diverse partners")
        print(f"Testing against {sum(len(test_set[algo]) for algo in test_set)} unseen partners")

        # ===== AHT TRAINING EXECUTION =====
        print("Starting Ad Hoc Teamwork training...")
        env = assistax.make(config["ENV_NAME"], **config["ENV_KWARGS"])
        
        # Create training function with zoo partner loading
        train_jit = jax.jit(
            make_train(
                config,
                save_train_state=True,
                load_zoo=load_zoo_dict_train  # Train against diverse partner set
            ),
            device=jax.devices()[config["DEVICE"]]
        )
        
        # Execute AHT training
        out = jax.vmap(train_jit, in_axes=(0, None, None, None))(
            train_rngs,
            config["LR"], config["ENT_COEF"], config["CLIP_EPS"]
        )

        # ===== SAVE TRAINING RESULTS =====
        print("Saving training results...")
        
        # Save training metrics (excluding large training states)
        EXCLUDED_METRICS = ["train_state"]
        jnp.save("metrics.npy", {
            key: val
            for key, val in out["metrics"].items()
            if key not in EXCLUDED_METRICS
            },
            allow_pickle=True
        )

        # Save model parameters
        all_train_states = out["metrics"]["train_state"]
        final_train_state = out["runner_state"].train_state

        upload_model_parameters_to_wandb(all_train_states, final_train_state, config, env, run)

        # ===== PARTNER DATA COLLECTION (optional) =====
        if config.get("COLLECT_PARTNER_DATA", False):
            print("Collecting partner action diversity data...")
            collect_fn = make_collect_partner_data(
                config, load_zoo_dict_test, batchify, unbatchify, RunnerState
            )
            collect_rng = jax.random.key(config["SEED"] + 999)
            # Use seed-0 trained policy for collection
            final_train_state_seed0 = _tree_take(final_train_state, 0, axis=0)
            collect_jit = jax.jit(collect_fn)
            partner_actions, partner_obs = collect_jit(collect_rng, final_train_state_seed0)
            jnp.save("partner_actions.npy", partner_actions, allow_pickle=False)
            jnp.save("partner_obs.npy", partner_obs, allow_pickle=False)
            print(f"Saved partner_actions.npy {partner_actions.shape} and partner_obs.npy {partner_obs.shape}")

        # ===== GENERALIZATION EVALUATION SETUP =====
        print("Setting up generalization evaluation...")
        
        # Calculate evaluation batching for memory efficiency
        batch_dims = jax.tree.leaves(_tree_shape(all_train_states.params))[:2]
        n_sequential_evals = int(jnp.ceil(
            config["NUM_EVAL_EPISODES"] * jnp.prod(jnp.array(batch_dims))
            / config["GPU_ENV_CAPACITY"]
        ))
        
        def _flatten_and_split_trainstate(trainstate):
            """
            Flatten training states across batch dimensions and split for sequential evaluation.
            
            This operation is JIT compiled for memory efficiency during evaluation.
            """
            flat_trainstate = jax.tree.map(
                lambda x: x.reshape((x.shape[0] * x.shape[1], *x.shape[2:])),
                trainstate
            )
            return _tree_split(flat_trainstate, n_sequential_evals)
        
        split_trainstate = jax.jit(_flatten_and_split_trainstate)(all_train_states)

        # Create evaluation environments for both train and test partner sets
        eval_train_env, run_eval_train = make_evaluation(config, load_zoo=load_zoo_dict_train)
        eval_test_env, run_eval_test = make_evaluation(config, load_zoo=load_zoo_dict_test)
        
        # Configure evaluation logging
        eval_log_config = EvalInfoLogConfig(
            env_state=False,
            done=True,
            action=False,
            value=False,
            reward=True,
            log_prob=False,
            obs=False,
            info=False,
            avail_actions=False,
            env_metrics=config.get("SAVE_METRICS", True)
        )

        # ===== DUAL EVALUATION EXECUTION =====
        print("Running dual evaluation (train vs test partners)...")
        
        # JIT compile evaluation functions for efficiency
        eval_train_jit = jax.jit(run_eval_train, static_argnames=["log_eval_info"])
        eval_train_vmap = jax.vmap(eval_train_jit, in_axes=(None, 0, None))
        eval_test_jit = jax.jit(run_eval_test, static_argnames=["log_eval_info"])
        eval_test_vmap = jax.vmap(eval_test_jit, in_axes=(None, 0, None))
        
        # Evaluate against training partners (seen during training)
        print("Evaluating against training partners...")
        evals_train = _concat_tree([
            eval_train_vmap(eval_rng, ts, eval_log_config)
            for ts in tqdm(split_trainstate, desc="Train partner evaluation")
        ])
        evals_train = jax.tree.map(
            lambda x: x.reshape((*batch_dims, *x.shape[1:])),
            evals_train
        )
        
        # Evaluate against test partners (unseen during training - zero-shot generalization)
        print("Evaluating against test partners (zero-shot coordination)...")
        evals_test = _concat_tree([
            eval_test_vmap(eval_rng, ts, eval_log_config)
            for ts in tqdm(split_trainstate, desc="Test partner evaluation")
        ])
        evals_test = jax.tree.map(
            lambda x: x.reshape((*batch_dims, *x.shape[1:])),
            evals_test
        )

        # ===== PERFORMANCE ANALYSIS =====
        print("Computing performance metrics...")
        
        # Compute returns for both train and test evaluations
        train_first_episode_returns = _compute_episode_returns(evals_train)
        train_first_episode_returns = train_first_episode_returns["__all__"]
        train_mean_episode_returns = train_first_episode_returns.mean(axis=-1)
        
        test_first_episode_returns = _compute_episode_returns(evals_test)
        test_first_episode_returns = test_first_episode_returns["__all__"]
        test_mean_episode_returns = test_first_episode_returns.mean(axis=-1)

        # Save evaluation results
        jnp.save("train_returns.npy", train_mean_episode_returns)
        jnp.save("test_returns.npy", test_mean_episode_returns)

        # ===== WANDB METRIC LOGGING =====
        log_all_metrics_zsc(config, out, evals_train, evals_test, env)
        upload_eval_data_to_wandb(evals_train, config, run, suffix="_train_partners")
        upload_eval_data_to_wandb(evals_test, config, run, suffix="_test_partners")

        # ===== GENERALIZATION ANALYSIS =====
        print("\nAd Hoc Teamwork Results Summary:")
        print(f"Performance with training partners: {train_mean_episode_returns.mean():.2f} ± {train_mean_episode_returns.std():.2f}")
        print(f"Performance with test partners: {test_mean_episode_returns.mean():.2f} ± {test_mean_episode_returns.std():.2f}")

        # ===== VISUALIZATION AND RENDERING =====
        print("Creating episode visualizations...")

        render_log_config = EvalInfoLogConfig(
            env_state=True,
            done=True,
            action=False,
            value=False,
            reward=True,
            log_prob=False,
            obs=False,
            info=False,
            avail_actions=False,
        )

        # Free memory before rendering
        print("Freeing memory before rendering...")
        del out
        del evals_train
        del evals_test
        del all_train_states
        del split_trainstate
        time.sleep(5)

        import gc
        gc.collect()
        jax.clear_caches()

        # Render using train-partner eval environment
        render_eval_env, render_run_eval = make_evaluation(config, load_zoo=load_zoo_dict_train)
        render_config = config
        render_config["NUM_EVAL_EPISODES"] = 1
        render_eval_jit = jax.jit(
            render_run_eval,
            static_argnames=["log_eval_info"],
        )
        eval_final = render_eval_jit(eval_rng, _tree_take(final_train_state, 0, axis=0), render_log_config)

        # Select worst, median, best episodes
        first_episode_done = jnp.cumsum(eval_final.done["__all__"], axis=0, dtype=bool)
        first_episode_rewards = eval_final.reward["__all__"] * (1 - first_episode_done)
        first_episode_returns = first_episode_rewards.sum(axis=0)
        episode_argsort = jnp.argsort(first_episode_returns, axis=-1)

        worst_idx = episode_argsort.take(0, axis=-1)
        best_idx = episode_argsort.take(-1, axis=-1)
        median_idx = episode_argsort.take(episode_argsort.shape[-1] // 2, axis=-1)

        worst_episode = _take_episode(
            eval_final.env_state.env_state.pipeline_state, first_episode_done,
            time_idx=-1, eval_idx=worst_idx,
        )
        median_episode = _take_episode(
            eval_final.env_state.env_state.pipeline_state, first_episode_done,
            time_idx=-1, eval_idx=median_idx,
        )
        best_episode = _take_episode(
            eval_final.env_state.env_state.pipeline_state, first_episode_done,
            time_idx=-1, eval_idx=best_idx,
        )
        episodes_dict = {
            'worst': worst_episode,
            'median': median_episode,
            'best': best_episode,
        }

        if config.get("SAVE_HTML_RENDER", True):
            upload_html_visualizations_to_wandb(render_eval_env, episodes_dict, run)

        if config.get("RENDER_MUJOCO_TRAJECTORIES", True):
            upload_mujoco_trajectories_to_wandb(render_eval_env, episodes_dict, run)

        if config.get("RENDER_VIDEOS", False):
            try:
                upload_mujoco_videos_to_wandb(
                    render_eval_env,
                    episodes_dict,
                    run,
                    fps=config.get("VIDEO_FPS", 30),
                    quality=config.get("VIDEO_QUALITY", "high"),
                    width=config.get("VIDEO_WIDTH", 1280),
                    height=config.get("VIDEO_HEIGHT", 720),
                )
            except Exception as e:
                print(f"Warning: Video rendering failed: {e}")
                print("Continuing without videos...")

        print("\nTraining and evaluation completed successfully!")

        if config.get("PRINT_MEMORY_STATS", False):
            print_memory_stats(f"IPPO AHT {config['EXP_ID']}")


if __name__ == "__main__":
    main()


