defaults:
  - network: ff_ps
  - _self_

ENV_NAME: scratchitch
ENV_KWARGS:
  ctrl_cost_weight: 0
  homogenisation_method: max
  backend: mjx
  disability:
    joint_idx: 13
    joint_restriction_factor: 1e-3
TOTAL_TIMESTEPS: 1e7
NUM_STEPS: 256
NUM_ENVS: 256
NUM_SEEDS: 1
SEED: 0

# RL HYPERPARAMETERS
UPDATE_EPOCHS: 4
NUM_MINIBATCHES: 4
ANNEAL_LR: False
LR: 2.5e-4
ENT_COEF: 1e-4
CLIP_EPS: 0.2
SCALE_CLIP_EPS: False
RATIO_CLIP_EPS: False
GAMMA: 0.99
GAE_LAMBDA: 0.95
VF_COEF: 1.0
MAX_GRAD_NORM: 0.5
ADAM_EPS: 1e-8

# COMPUTE OPTIONS
ADVANTAGE_UNROLL_DEPTH: 8
DISABLE_JIT: False
DEVICE: 0

# SWEEPER SETTINGS
SWEEP:
  num_configs: 4
  lr:
    min: -4.0
    max: -3.0
  ent_coef: false
  clip_eps: false

hydra:
  job:
    chdir: true
  run:
    dir: outputs/mabrax/${ENV_NAME}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/mabrax/${ENV_NAME}/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${SEED}
