defaults:
  - network: ff_nps
  - _self_

ENV_NAME: scratchitch 
ALG: IPPO
ENV_KWARGS:
  ctrl_cost_weight: 0
  homogenisation_method: max
  backend: mjx
  het_reward: False # TODO Has to be true for pushcoop otherwise false, but would be better to set this automatically based on the env. 
  episode_length: 1000
  #disability:
  #  joint_idx: 13 # 13 = right shoulder, 14 = right elbow ; 12 = right shoulder but which direction?
  #  joint_restriction_factor: 0.7
  #  joint_strength: 0.7
  #  tremor_magnitude: 0.0
#  sparse_rewards: 
#    mode: periodic
#    period: 100 
#    accumulate: True
  #preference_rewards:
  #  preference_weights:
  #    speed_preference: 0.25
  #    force_preference: 0.35
  #    action_efficiency: 0.15
  #    touch_penalty: -0.03
    #preference_ranges:
    #  speed_range: [0.06, 0.14]
    #  force_range: [1.5, 3.5]
    #  max_action_magnitude: 0.8
    #touch_threshold: 0.3
  #  variable_names:
  #    speed: "ee_speed"
  #    force: "ee_force"
  #    action_magnitude: "action_magnitude"
      # contact_forces: "contact_forces"  


TOTAL_TIMESTEPS: 3e7 
NUM_STEPS: 64
NUM_ENVS: 1024 
NUM_SEEDS: 2 
SEED: 0 
NUM_EVAL_EPISODES: 12 

# RL HYPERPARAMETERS
UPDATE_EPOCHS: 4
NUM_MINIBATCHES: 4
ANNEAL_LR: False
LR: 0.0010507666738703847
ENT_COEF: 1e-4
CLIP_EPS:  0.2
SCALE_CLIP_EPS: False
RATIO_CLIP_EPS: False
GAMMA: 0.99
GAE_LAMBDA: 0.95
VF_COEF: 1.0
MAX_GRAD_NORM: 0.5
ADAM_EPS: 1e-8

# COMPUTE OPTIONS
GPU_ENV_CAPACITY: 8192
ADVANTAGE_UNROLL_DEPTH: 8
DISABLE_JIT: False
DEVICE: 0

# EVAL TRAIN STATE
eval:
  path:
    human: ./path/to/human.safetensors
    robot: ./path/to/robot.safetensors
    all: ./path/to/all.safetensors
# SWEEPER SETTINGS
sweep:
  num_configs: 4
  lr:
    min: -4.0
    max: -3.0
  ent_coef: false
  clip_eps: false

# Visualization settings
SAVE_MUJOCO_TRAJECTORIES: True  # Always save trajectories (minimal overhead)
SAVE_HTML_RENDER: True
RENDER_VIDEOS: False  # Set to True for important runs
VIDEO_FPS: 30  # Frames per second for videos
VIDEO_WIDTH: 1920 # Video width in pixels
VIDEO_HEIGHT: 1080  # Video height in pixels
VIDEO_QUALITY: "high"  # "low", "medium", or "high"
EXP_ID: ${oc.env:EXP_ID,${now:%Y-%m-%d_%H-%M-%S}}   # Unique experiment identifier based on timestamp

# WandB Params
ENTITY: "lh-from-kb" 
PROJECT: "assistax-dev"
WANDB_MODE: "online" # "disabled" or "online"
EXP_TAGS: ["IPPO","FF","NoPS","Vectorized", "NoPref"]


# hydra:
#   job:
#     chdir: true
#   run:
#     dir: outputs/${ENV_NAME}/${ALG}/${now:%Y-%m-%d}/${now:%H-%M-%S}
#   sweep:
#     dir: multirun/${ENV_NAME}/${now:%Y-%m-%d}/${now:%H-%M-%S}
#     subdir: seed_${SEED}_$env_setting${ENV_KWARGS.sparse_rewards.period}