defaults:
  - network: ff_nps
  - _self_

ENV_NAME: scratchitch 

ENV_KWARGS:
  ctrl_cost_weight: 0
  homogenisation_method: max
  backend: mjx
  het_reward: False # Has to be true for pushcoop otherwise false
  # episode_length: 1000
  disability:
    joint_idx: 13
    joint_restriction_factor: 1.0
    joint_strength: 1.0
    tremor_magnitude: 0.0

  # pixel_obs:
  #   hw: 64
  #   frame_stack: 3
  #   return_float32: False
  #   cache_objects: False
  #   n_envs: 2  # if cachinig same as NUM_ENVS

TOTAL_TIMESTEPS: 10e5
NUM_STEPS: 64
NUM_ENVS: 256
NUM_SEEDS: 3
SEED: 0
NUM_EVAL_EPISODES: 16

# RL HYPERPARAMETERS
UPDATE_EPOCHS: 4
NUM_MINIBATCHES: 4
ANNEAL_LR: False
LR: 0.0010507666738703847
ENT_COEF: 1e-4
CLIP_EPS:  0.2
SCALE_CLIP_EPS: False
RATIO_CLIP_EPS: False
GAMMA: 0.99
GAE_LAMBDA: 0.95
VF_COEF: 1.0
MAX_GRAD_NORM: 0.5
ADAM_EPS: 1e-8

# COMPUTE OPTIONS
GPU_ENV_CAPACITY: 8192
ADVANTAGE_UNROLL_DEPTH: 8
DISABLE_JIT: False
DEVICE: 0

# EVAL TRAIN STATE
eval:
  path:
    human: /home/leo/assistax/JaxMARL/baselines/outputs/mabrax/pushcoop/2025-05-13/11-02-56/robot1.safetensors
    robot: /home/leo/assistax/JaxMARL/baselines/outputs/mabrax/pushcoop/2025-05-13/11-02-56/robot2.safetensors
    all: /home/leo/assistax/JaxMARL/baselines/outputs/mabrax/pushcoop/2025-05-13/11-02-56/all_params.safetensors
# SWEEPER SETTINGS
sweep:
  num_configs: 4
  lr:
    min: -4.0
    max: -3.0
  ent_coef: false
  clip_eps: false

# CROSSPLAY SETTINGS
crossplay:
  paths:
    agent_0: /path/to/agent_0.safetensors
    agent_1: /path/to/agent_1.safetensors

hydra:
  job:
    chdir: true
  run:
    dir: outputs/mabrax/${ENV_NAME}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/mabrax/${ENV_NAME}/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: seed_${SEED}
